import React, { useEffect, useState } from 'react';
import { FileText, ImageIcon, Download, Database, ShieldCheck } from 'lucide-react';
import { api, type ReportsPayload } from '../utils/api';
import { Badge, Button, Card, EmptyState, Spinner } from '../components/ui';

const DOC_LABELS: Record<string, string> = {
  'classification_report.txt': 'Classification report',
  'model_results_summary.txt': 'Model results summary',
  'data_quality.txt': 'Data quality',
  'error_analysis.txt': 'Error analysis',
  'robustness.txt': 'Robustness audit',
  'scientific_validity.txt': 'Scientific validity',
  'feature_importance.csv': 'Feature importance (CSV)',
  'model_comparison.csv': 'Model comparison (CSV)',
};

export function ReportsView() {
  const [data, setData] = useState<ReportsPayload | null>(null);
  const [selectedDoc, setSelectedDoc] = useState<{ name: string; text: string } | null>(null);

  useEffect(() => {
    let mounted = true;
    api
      .reports()
      .then((r) => mounted && setData(r))
      .catch(() => mounted && setData(null));
    return () => {
      mounted = false;
    };
  }, []);

  if (!data) {
    return (
      <div className="flex items-center justify-center py-32">
        <Spinner className="h-6 w-6 text-brand" />
      </div>
    );
  }

  const docs = Object.entries(data.documents ?? {});
  const images = Object.entries(data.images ?? {}).filter(([, url]) => url);

  return (
    <div className="space-y-6">
      <div className="grid gap-6 lg:grid-cols-2">
        {/* EDA images */}
        <Card title="Exploratory data analysis" subtitle="Generated by eda.py" >
          {data.eda_images.length === 0 ? (
            <EmptyState icon={<ImageIcon className="h-5 w-5" />} title="No EDA plots" message="Run python eda.py to generate exploratory plots in reports/eda/" />
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {data.eda_images.map((img) => (
                <div key={img.name} className="overflow-hidden rounded-xl border border-line">
                  <img src={img.url} alt={img.name} loading="lazy" className="w-full" />
                </div>
              ))}
            </div>
          )}
        </Card>

        {/* Model images */}
        <Card title="Model artifacts" subtitle="Confusion matrix and feature importance">
          {images.length === 0 ? (
            <EmptyState icon={<Database className="h-5 w-5" />} title="No model images" message="Train and evaluate models to produce confusion_matrix.png and feature_importance.png" />
          ) : (
            <div className="grid gap-4">
              {images.map(([name, url]) => (
                <div key={name} className="overflow-hidden rounded-xl border border-line">
                  <p className="border-b border-line bg-surface-2 px-4 py-2 text-[12.5px] font-semibold text-ink-2">
                    {name.replace('.png', '').replace(/_/g, ' ')}
                  </p>
                  <img src={url!} alt={name} loading="lazy" className="w-full" />
                </div>
              ))}
              {data.stats.dataset_exists && (
                <div className="mt-2 flex items-center justify-between rounded-xl bg-surface-2 p-4">
                  <div>
                    <p className="text-[13px] font-semibold text-ink">Engineered dataset</p>
                    <p className="text-[12px] text-ink-3">{data.stats.total_videos} videos · {data.stats.n_features} features</p>
                  </div>
                  <a href="/api/dataset.csv">
                    <Button variant="secondary"><Download className="h-4 w-4" /> CSV</Button>
                  </a>
                </div>
              )}
            </div>
          )}
        </Card>
      </div>

      {/* Documents */}
      <Card title="Validation & audit documents" subtitle="Human-readable reports produced by the pipeline">
        {docs.length === 0 ? (
          <EmptyState icon={<FileText className="h-5 w-5" />} title="No documents found" message="Run the pipeline's validation and reporting scripts to generate documents in reports/" />
        ) : (
          <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
            {docs.map(([name, text]) => (
              <button
                key={name}
                onClick={() => setSelectedDoc({ name, text })}
                className="group flex items-center gap-3 rounded-xl border border-line bg-surface-2 p-4 text-left transition-all hover:border-brand/40 hover:bg-brand-50/40"
              >
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-ink-2 group-hover:bg-brand-50 group-hover:text-brand">
                  <FileText className="h-4 w-4" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="truncate text-[13.5px] font-semibold text-ink">
                    {DOC_LABELS[name] ?? name}
                  </p>
                  <p className="truncate font-mono text-[11px] text-ink-3">{name}</p>
                </div>
                <Badge tone="slate">{text.length} ch</Badge>
              </button>
            ))}
          </div>
        )}

        {selectedDoc && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-6">
            <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={() => setSelectedDoc(null)} />
            <div className="relative flex max-h-[80vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl">
              <div className="flex items-center justify-between border-b border-line px-5 py-4">
                <div className="flex items-center gap-2">
                  <ShieldCheck className="h-4 w-4 text-brand" />
                  <span className="text-[14px] font-semibold text-ink">
                    {DOC_LABELS[selectedDoc.name] ?? selectedDoc.name}
                  </span>
                </div>
                <button
                  onClick={() => setSelectedDoc(null)}
                  className="rounded-lg px-2.5 py-1 text-[13px] font-semibold text-ink-3 hover:bg-surface-3"
                >
                  Close
                </button>
              </div>
              <pre className="flex-1 overflow-auto whitespace-pre-wrap break-words px-5 py-4 font-mono text-[12px] leading-relaxed text-ink-2">
                {selectedDoc.text}
              </pre>
            </div>
          </div>
        )}
      </Card>
    </div>
  );
}