import os
import re
import hashlib
import subprocess
import sys
import threading
import time
import uuid
from pathlib import Path

import cv2
import pandas as pd
from flask import (
    Flask,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    send_from_directory,
    send_file,
    abort,
    jsonify,
)

import shot_rating

import config


BASE_DIR = Path(__file__).resolve().parent
INPUT_VIDEOS = BASE_DIR / "input_videos"
OUTPUT_DATA = BASE_DIR / "output_data"
# Annotated analysis videos live in output_videos/, never in input_videos
# (see config.py). This is the structural fix that stops generated files
# from being picked up as inputs.
ANALYSIS_VIDEOS = config.ANALYSIS_VIDEOS
OUTPUT_VIDEOS = ANALYSIS_VIDEOS  # legacy alias used below
REPORTS_DIR = BASE_DIR / "reports"
# served as the app frontend; the old Jinja templates remain as a fallback.
WEB_DIST = BASE_DIR / "web-main" / "web-main" / "dist"

ALLOWED_EXTENSIONS = {".mp4", ".avi", ".mov", ".mkv"}
# Canonical shot classes. Each one owns a folder under input_videos/ whose name
# is exactly the slug below, so a processed clip is always discoverable from its
# class alone.
SHOT_TYPES = ["cut", "defence", "drive", "flick", "pull shot", "unknown"]
SHOT_TYPE_LABELS = {
    "cut": "Cut",
    "defence": "Defence",
    "drive": "Drive",
    "flick": "Flick",
    "pull shot": "Pull Shot",
    "unknown": "Unknown",
}


def normalise_shot_type(value):
    """Return the canonical slug for a shot-type label, or None if unknown.

    "Pull Shot" is a multi-word class, so callers may spell it with a space
    ("pull shot"), with an underscore ("pull_shot") or in mixed case. All three
    collapse to the single slug that matches the input_videos/ folder name, so
    uploads can never land in a second, parallel pull-shot folder.
    """
    if value is None:
        return None
    slug = " ".join(str(value).strip().lower().replace("_", " ").split())
    return slug if slug in SHOT_TYPES else None

# Filename suffixes generated by the pipeline (analysis videos, transcode
# intermediates). Any file matching one of these is NEVER treated as an input
# clip: upload dedup and the batch worker skip them so freshly generated
# analysis videos can never be re-uploaded / re-processed. The web app also
# never writes generated files into input_videos anymore (see config.py), so
# this is a safety net for legacy files.
GENERATED_SUFFIXES = config.GENERATED_SUFFIXES


def is_generated_video(filename):
    """Return True when a filename belongs to a generated pipeline output."""
    return config.is_generated_filename(filename)

# Columns (from biomechanics_analyzer.py) used on the results page.
IMPACT_ANGLE_COLUMNS = [
    "left_elbow_angle_at_impact",
    "right_elbow_angle_at_impact",
    "left_knee_angle_at_impact",
    "right_knee_angle_at_impact",
    "left_shoulder_angle_at_impact",
    "right_shoulder_angle_at_impact",
    "left_hip_angle_at_impact",
    "right_hip_angle_at_impact",
]
IMPACT_ANGLE_LABELS = {
    "left_elbow_angle_at_impact": "Left Elbow",
    "right_elbow_angle_at_impact": "Right Elbow",
    "left_knee_angle_at_impact": "Left Knee",
    "right_knee_angle_at_impact": "Right Knee",
    "left_shoulder_angle_at_impact": "Left Shoulder",
    "right_shoulder_angle_at_impact": "Right Shoulder",
    "left_hip_angle_at_impact": "Left Hip",
    "right_hip_angle_at_impact": "Right Hip",
}

app = Flask(__name__)
app.secret_key = os.environ.get(
    "FLASK_SECRET_KEY", "cricket-biomechanics-dev-secret"
)
# Reject oversized uploads early (Flask responds 413). Value in bytes.
app.config["MAX_CONTENT_LENGTH"] = 512 * 1024 * 1024


def ensure_storage_directories():
    """Create the expected app folders so the web UI works on a fresh clone."""
    for folder in (INPUT_VIDEOS, OUTPUT_DATA, REPORTS_DIR, ANALYSIS_VIDEOS,
                   config.UPLOADS):
        folder.mkdir(parents=True, exist_ok=True)
    (REPORTS_DIR / "eda").mkdir(parents=True, exist_ok=True)


ensure_storage_directories()


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------
def allowed_file(filename):
    return Path(filename).suffix.lower() in ALLOWED_EXTENSIONS


def safe_filename(name):
    keep = "".join(c for c in name if c.isalnum() or c in "-_")
    return keep or "video"


def video_content_hash(path, chunk_size=1024 * 1024):
    """Return a stable digest used to prevent identical uploads."""
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


# Serialises the dedup-then-move upload step so two simultaneous identical
# submissions can never create two input files.
UPLOAD_LOCK = threading.Lock()
# SHA-256 digests of uploads currently being scheduled into the pipeline.
# A repeat submit for the same clip while one is already in flight is
# short-circuited instead of written a second time.
INFLIGHT_UPLOADS = set()


def find_existing_video(path, digest=None):
    """Find an existing uploaded source with identical contents.

    Only files with the same byte size as the upload are hashed (fast
    pre-filter), and generated pipeline outputs are never treated as inputs.
    """
    if digest is None:
        digest = video_content_hash(path)
    try:
        size = path.stat().st_size
    except OSError:
        return None
    for candidate in INPUT_VIDEOS.rglob("*"):
        if candidate == path or not candidate.is_file():
            continue
        if candidate.suffix.lower() not in ALLOWED_EXTENSIONS:
            continue
        if is_generated_video(candidate.name):
            continue
        try:
            if candidate.stat().st_size != size:
                continue
        except OSError:
            continue
        if video_content_hash(candidate) == digest:
            return candidate
    return None


def make_unique_path(folder, stem, ext):
    """Return a Path inside `folder` that does not already exist.

    Appends -1, -2, ... to the stem when a name collision exists so an
    uploaded file never silently overwrites an existing one. The name is also
    checked against the processed-output folders so two uploaded clips sharing
    a stem will never write into the same output_data / analysis folder.
    """
    folder.mkdir(parents=True, exist_ok=True)

    def _taken(candidate_stem):
        candidate = folder / f"{candidate_stem}{ext}"
        if candidate.exists():
            return True
        # Same stem must not collide with an existing processed video.
        if (OUTPUT_DATA / candidate_stem).exists():
            return True
        if (ANALYSIS_VIDEOS / f"{candidate_stem}_analysis.mp4").exists():
            return True
        return False

    stem0 = stem
    counter = 1
    while _taken(stem):
        stem = f"{stem0}-{counter}"
        counter += 1
    return folder / f"{stem}{ext}"


def run_pipeline(video_path):
    """Run the existing per-video pipeline via process_video.py.

    Returns the process stdout/stderr so errors can be surfaced cleanly,
    without leaking raw tracebacks to the user.
    """
    command = [
        sys.executable,
        str(BASE_DIR / "process_video.py"),
        str(video_path),
    ]
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            cwd=str(BASE_DIR),
            timeout=3600,
            creationflags=config.NO_CONSOLE_FLAGS,
        )
    except (subprocess.TimeoutExpired,
            subprocess.SubprocessError, OSError) as exc:
        print(f"[run_pipeline] {exc}")
        return type("Result", (), {
            "returncode": 1, "stdout": "", "stderr": str(exc)
        })()
    return result


# ---------------------------------------------------------------------------
# Background processing jobs: uploads run off the request thread so the web
# UI never freezes while MediaPipe + rendering churn through a clip.
# ---------------------------------------------------------------------------
PIPELINE_STEP_LABELS = {
    "main.py": "Detecting player pose & landmarks",
    "angle_calculator.py": "Calculating joint angles",
    "phase_detector.py": "Detecting batting phases",
    "biomechanics_analyzer.py": "Extracting biomechanics features",
    "shot_rater.py": "Rating the shot (0-10)",
    "injury_risk.py": "Screening injury & batsman safety",
    "output_video.py": "Rendering annotated analysis video",
}
PIPELINE_JOBS = {}
PIPELINE_JOBS_LOCK = threading.Lock()

# Batch processing state (keyed by batch_id)
BATCH_JOBS = {}
BATCH_JOBS_LOCK = threading.Lock()
MAX_JOBS = 400


def _prune_old_jobs():
    """Drop finished jobs older than a day so the registry cannot grow forever."""
    cutoff = time.time() - 86400
    with PIPELINE_JOBS_LOCK:
        for jid in [j for j, job in PIPELINE_JOBS.items()
                    if job.get("done") and (job.get("finished_at") or 0) < cutoff]:
            PIPELINE_JOBS.pop(jid, None)


def _pipeline_worker(job_id):
    job = PIPELINE_JOBS[job_id]
    job["current"] = "Starting analysis…"
    job["started_at"] = time.time()
    video_path = Path(job["video_path"])
    command = [
        sys.executable,
        str(BASE_DIR / "process_video.py"),
        str(video_path),
    ]
    try:
        env = dict(os.environ)
        env["PYTHONUNBUFFERED"] = "1"
        proc = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            cwd=str(BASE_DIR),
            env=env,
            creationflags=config.NO_CONSOLE_FLAGS,
        )
        for line in proc.stdout:
            line = line.strip()
            if line.startswith("RUNNING:"):
                matched = False
                for token, label in PIPELINE_STEP_LABELS.items():
                    if token in line:
                        if label not in job["steps"]:
                            job["steps"].append(label)
                        job["current"] = label
                        matched = True
                        break
                if not matched:
                    job["current"] = line[len("RUNNING:"):].strip()
            elif "COMPLETE" in line:
                job["current"] = "Finalising results…"
        proc.wait()
        job["ok"] = proc.returncode == 0
        if not job["ok"]:
            job["error"] = "Processing failed on the server — see the console log."
    except Exception as exc:
        print(f"[pipeline] job {job_id} crashed: {exc}")
        job["ok"] = False
        job["error"] = f"Processing crashed: {exc}"

    if job["ok"]:
        job["video_name"] = video_path.stem
    job["current"] = "Done" if job["ok"] else "Failed"
    with PIPELINE_JOBS_LOCK:
        job["done"] = True
        job["finished_at"] = time.time()
    _release_inflight(job)


def _release_inflight(job):
    """Release the upload-dedup lock once a queued clip finishes processing."""
    digest = job.get("digest")
    if digest:
        with UPLOAD_LOCK:
            INFLIGHT_UPLOADS.discard(digest)


def load_video_results(video_name):
    """Read biomechanics results for a processed video from its CSV files."""
    video_name = Path(video_name).name
    folder = OUTPUT_DATA / video_name
    features_file = folder / "biomechanics_features.csv"
    landmarks_file = folder / "batting_landmarks.csv"

    data = {
        "video_name": video_name,
        "frames": None,
        "found": features_file.exists(),
        "impact_angles": {},
        "metrics": {},
        "features": {},
        "rating": None,
    }

    if landmarks_file.exists():
        try:
            data["frames"] = len(
                pd.read_csv(landmarks_file, usecols=["frame"])
            )
        except Exception:
            data["frames"] = None

    if not features_file.exists():
        return data

    try:
        row = pd.read_csv(features_file).iloc[0].to_dict()
    except Exception:
        return data

    data["features"] = row

    metric_keys = [
        "impact_frame",
        "impact_time_ms",
        "downswing_duration_ms",
        "followthrough_duration_ms",
        "maximum_movement_score",
        "average_movement_score",
    ]
    for key in metric_keys:
        if key in row:
            data["metrics"][key] = row[key]

    for col in IMPACT_ANGLE_COLUMNS:
        if col in row:
            data["impact_angles"][col] = row[col]

    # Shot rating - computed deterministically by the reusable module. The
    # per-frame extra data activates balance/backlift/stride factors. Any
    # per-video data glitch must never 500 the whole results page, so a
    # failure here degrades to a missing rating instead.
    data["rating"] = None
    try:
        data["rating"] = shot_rating.rating_to_dict(
            shot_rating.rate_shot(
                row, extra=shot_rating.build_extra(video_name)
            )
        )
    except Exception as exc:
        print(f"[load_video_results] rating failed for {video_name}: {exc}")

    return data


def make_angle_plot(video_name):
    """Generate a multi-panel angle time-series plot from batting_angles.csv.

    Returns the filename of the saved plot, or None on failure. The plot is
    only regenerated when missing - results pages stay fast on repeat loads.
    """
    plot_name = "angle_plot.png"
    out = OUTPUT_DATA / video_name / plot_name
    if out.exists():
        return plot_name
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        angles_file = OUTPUT_DATA / video_name / "batting_angles.csv"
        if not angles_file.exists():
            return None

        df = pd.read_csv(angles_file)
        angle_cols = [
            c for c in df.columns
            if c not in {"frame", "timestamp_ms"}
        ]
        if not angle_cols:
            return None

        t_ms = df["timestamp_ms"].to_numpy()

        n = len(angle_cols)
        cols = 2
        rows = int((n + 1) / 2)
        fig, axes = plt.subplots(rows, cols, figsize=(12, 3.2 * rows))
        axes = axes.flatten()

        for idx, col in enumerate(angle_cols):
            ax = axes[idx]
            ax.plot(t_ms, df[col], lw=1.5)
            ax.set_title(col, fontsize=9)
            ax.set_xlabel("time (ms)")
            ax.set_ylabel("angle (deg)")
            ax.grid(True, alpha=0.3)

        for idx in range(n, len(axes)):
            axes[idx].axis("off")

        fig.suptitle(f"Joint Angles - {video_name}", fontsize=13)
        fig.tight_layout(rect=[0, 0, 1, 0.97])

        plot_name = "angle_plot.png"
        out = OUTPUT_DATA / video_name / plot_name
        fig.savefig(out, dpi=130)
        plt.close(fig)
        return plot_name
    except Exception as exc:
        print(f"[make_angle_plot] {exc}")
        return None


def load_dataset_stats():
    """Return dataset stats read dynamically from the dataset CSV.

    Falls back gracefully when the dataset has not been built yet.
    """
    stats = {
        "total_videos": 0,
        "n_classes": 0,
        "class_names": [],
        "distribution": {},
        "n_features": 0,
        "dataset_exists": False,
        "has_ml_reports": {
            "comparison": (REPORTS_DIR / "model_comparison.csv").exists(),
            "confusion": (REPORTS_DIR / "confusion_matrix.png").exists(),
            "importance": (REPORTS_DIR / "feature_importance.png").exists(),
            "summary": (REPORTS_DIR / "model_results_summary.txt").exists(),
        },
    }

    dataset_files = [
        OUTPUT_DATA / "cricket_biomechanics_dataset_engineered.csv",
        OUTPUT_DATA / "cricket_biomechanics_dataset_cleaned.csv",
        OUTPUT_DATA / "cricket_biomechanics_dataset.csv",
    ]
    chosen = None
    for path in dataset_files:
        if path.exists():
            chosen = path
            break

    if chosen is None:
        return stats

    try:
        df = pd.read_csv(chosen)
        stats["dataset_exists"] = True
        stats["total_videos"] = len(df)
        stats["distribution"] = (
            df["shot_type"].value_counts().to_dict()
            if "shot_type" in df.columns else {}
        )
        stats["class_names"] = list(stats["distribution"].keys())
        stats["n_classes"] = len(stats["class_names"])
        stats["n_features"] = len(
            [c for c in df.columns if c not in
             {"video_name", "shot_type"}]
        )
    except Exception as exc:
        print(f"[load_dataset_stats] {exc}")

    return stats


# --------------------------------------------------------------------------
# ML insights + recent videos + phase timeline helpers
# --------------------------------------------------------------------------
def load_ml_insights():
    """Read ML eval info (best model, accuracy, method) from report files."""
    insights = {
        "available": False,
        "dataset_size": None,
        "n_classes": None,
        "best_model": None,
        "evaluation": "Leave-One-Out CV (LOOCV)",
        "accuracy": None,
        "accuracy_raw": None,
        "comparison_table": None,  # list of dict rows
    }

    summary = REPORTS_DIR / "model_results_summary.txt"
    if summary.exists():
        try:
            text = summary.read_text(encoding="utf-8")
            m = re.search(r"Dataset size\s*:?\s*(\d+)", text, re.I)
            if m:
                insights["dataset_size"] = int(m.group(1))
            m = re.search(r"Best model\s*:?\s*([A-Za-z]+)", text)
            if m:
                insights["best_model"] = m.group(1)
            m = re.search(
                r"LOOCV accuracy\s*:?\s*([0-9.]+)",
                text, re.I
            )
            if m:
                insights["accuracy_raw"] = float(m.group(1))
                insights["accuracy"] = f"{float(m.group(1)) * 100:.1f}%"
            m = re.search(r"Shot classes\s*:?\s*(\d+)", text, re.I)
            if m:
                insights["n_classes"] = int(m.group(1))
        except Exception as exc:
            print(f"[load_ml_insights] summary: {exc}")

    comp = REPORTS_DIR / "model_comparison.csv"
    rows = []
    if comp.exists():
        try:
            df = pd.read_csv(comp)
            for _, r in df.iterrows():
                rows.append({
                    "model": r.get("model", ""),
                    "accuracy": r.get("accuracy"),
                    "f1_macro": r.get("f1_macro"),
                    "precision_macro": r.get("precision_macro"),
                    "recall_macro": r.get("recall_macro"),
                })
        except Exception as exc:
            print(f"[load_ml_insights] comparison: {exc}")

    if insights["best_model"] or insights["accuracy_raw"] is not None:
        insights["available"] = True
    insights["comparison_table"] = rows
    return insights


def load_recent_videos(limit=8):
    """Return recently processed videos with available metadata.

    A video is considered processed if it has a biomechanics_features.csv
    under its output_data/<name>/ folder. Ordered newest-first by mtime.
    """
    return _list_processed_videos()[:limit]


def _list_processed_videos():
    """Return *every* processed video as metadata dicts, newest first.

    Shared by the dashboard (recents) and the full analysis history page.
    """
    items = []
    if not OUTPUT_DATA.exists():
        return items

    features_file = OUTPUT_DATA / "cricket_biomechanics_dataset_engineered.csv"
    name_map = {}
    if features_file.exists():
        try:
            df = pd.read_csv(features_file)
            if "video_name" in df.columns and "shot_type" in df.columns:
                name_map = dict(
                    zip(df["video_name"].astype(str), df["shot_type"])
                )
        except Exception:
            name_map = {}

    for folder in OUTPUT_DATA.iterdir():
        if not folder.is_dir():
            continue
        feat = folder / "biomechanics_features.csv"
        if not feat.exists():
            continue
        name = folder.name
        shot = name_map.get(name, "")
        rating = None
        rating_file = folder / "shot_rating.csv"
        if rating_file.exists():
            try:
                rdf = pd.read_csv(rating_file)
                if not rdf.empty and "rating" in rdf.columns:
                    rating = float(rdf["rating"].iloc[0])
            except Exception:
                rating = None

        frames = None
        landmarks_file = folder / "batting_landmarks.csv"
        if landmarks_file.exists():
            try:
                frames = len(pd.read_csv(landmarks_file, usecols=["frame"]))
            except Exception:
                frames = None

        items.append((folder.name, shot, folder.stat().st_mtime,
                      rating, frames))

    items.sort(key=lambda t: t[2], reverse=True)
    out = []
    for name, shot, mtime, rating, frames in items:
        analysis = OUTPUT_VIDEOS / f"{name}_analysis.mp4"
        out.append({
            "name": name,
            "shot_type": shot,
            "rating": rating,
            "frames": frames,
            "processed_at": time.strftime(
                "%Y-%m-%d %H:%M", time.localtime(mtime)),
            "analysis_exists": analysis.exists(),
            "results_url": url_for("results", video_name=name,
                                   shot_type=shot) if shot else
                            url_for("results", video_name=name),
        })
    return out


def load_injury_data(video_name):
    """Read the injury risk / batsman safety outputs for a processed video.

    Returns a dict with the summary row and the list of detected flags, or an
    empty structure when the analysis has not been produced yet. Never raises -
    a missing/incomplete file degrades to "no data" instead of a 500.
    """
    video_name = Path(video_name).name
    folder = OUTPUT_DATA / video_name
    data = {
        "summary": None,
        "flags": [],
        "available": False,
    }
    summary_file = folder / "injury_risk_summary.csv"
    if summary_file.exists():
        try:
            row = pd.read_csv(summary_file).iloc[0]
            data["summary"] = {
                "safety_score": float(row.get("safety_score", 0.0)),
                "risk_level": str(row.get("risk_level", "")),
                "coverage": float(row.get("coverage", 0.0)),
                "n_flags": int(row.get("n_flags", 0)),
                "top_concern": str(row.get("top_concern", "")),
                "summary": str(row.get("summary", "")),
            }
            data["available"] = True
        except Exception as exc:
            print(f"[load_injury_data] summary failed for {video_name}: {exc}")

    flags_file = folder / "injury_risk.csv"
    if flags_file.exists():
        try:
            df = pd.read_csv(flags_file)
            for _, r in df.iterrows():
                data["flags"].append({
                    "metric": str(r.get("metric", "")),
                    "label": str(r.get("metric_label", "")),
                    "side": str(r.get("side", "")),
                    "severity": str(r.get("severity", "mild")),
                    "frames": int(r.get("frames", 0) or 0),
                    "pct": float(r.get("pct_total", 0.0) or 0.0),
                    "peak": float(r.get("peak_value", 0.0) or 0.0),
                    "units": str(r.get("value_units", "")),
                    "worst_phase": str(r.get("worst_phase", "")),
                    "description": str(r.get("description", "")),
                    "cue": str(r.get("cue", "")),
                })
        except Exception as exc:
            print(f"[load_injury_data] flags failed for {video_name}: {exc}")

    return data


def load_shot_classification(video_name):
    """Return the model-based shot classification for a processed clip.

    Produced by ml_model.classify_video() during the pipeline. The final
    class is "unknown" whenever the model was not confident about a
    supported shot, so the UI can surface Unknown while still showing the
    full biomechanics analysis.
    """
    import json

    path = OUTPUT_DATA / video_name / "shot_classification.json"
    if not path.exists():
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception as exc:
        print(f"[load_shot_classification] {video_name}: {exc}")
        return None


def load_phase_timeline(video_name):
    """Return phase segments + key frames from batting_phases.csv."""
    phases_file = OUTPUT_DATA / video_name / "batting_phases.csv"
    if not phases_file.exists():
        return None
    try:
        df = pd.read_csv(phases_file)
    except Exception:
        return None

    segs = []
    current = None
    for _, row in df.iterrows():
        ph = str(row["phase"])
        fr = int(row["frame"])
        if current is None or current["phase"] != ph:
            if current is not None:
                current["end"] = fr
            current = {"phase": ph, "start": fr, "end": None}
            segs.append(current)
        else:
            current["end"] = fr
    if current is not None and current["end"] is None:
        current["end"] = int(df["frame"].iloc[-1])

    total = int(df["frame"].iloc[-1]) if len(df) else 0
    impact = df[df["phase"] == "Impact"]["frame"]
    impact_frame = int(impact.iloc[len(impact) // 2]) if len(impact) else None

    return {
        "segments": segs,
        "total_frames": total,
        "impact_frame": impact_frame,
        "fps": None,
    }


def make_results_charts(video_name):
    """Generate chart PNGs for the results page from existing CSVs.

    Returns a dict of {chart_key: filename} for the ones that succeeded.
    Charts are only regenerated when missing - results pages stay fast on
    repeat loads.
    """
    expected = {"movement": "movement_chart.png",
                "joint_angles": "joint_angles_chart.png",
                "phase": "phase_chart.png"}
    folder = OUTPUT_DATA / video_name
    # Return cached charts if they already exist.
    cached = {k: v for k, v in expected.items() if (folder / v).exists()}
    if len(cached) == len(expected):
        return cached
    out = dict(cached)
    phases_file = folder / "batting_phases.csv"
    angles_file = folder / "batting_angles.csv"
    if not phases_file.exists():
        return out

    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        CHART_COLORS = {
            "Stance": "#3fa7ff",
            "Backlift": "#ffc34d",
            "Downswing": "#35e0a1",
            "Impact": "#ff5e7a",
            "Follow-through": "#b387ff",
        }

        df = pd.read_csv(phases_file)
        frames = df["frame"].to_numpy()

        # -- Movement score over time --------------------------------
        if "movement_smooth" in df.columns:
            fig, ax = plt.subplots(figsize=(9, 3.6), dpi=120)
            ax.plot(frames, df["movement_smooth"], color="#3fa7ff", lw=1.8)
            ax.fill_between(frames, df["movement_smooth"],
                            color="#3fa7ff", alpha=0.18)
            # phase shading
            for seg in df.groupby((df["phase"] != df["phase"].shift())
                                  .cumsum()):
                sub = seg[1]
                ph = sub["phase"].iloc[0]
                ax.axvspan(sub["frame"].iloc[0], sub["frame"].iloc[-1],
                           color=CHART_COLORS.get(ph, "#888"),
                           alpha=0.10, lw=0)
            ax.set_title("Movement Score Over Time", fontweight="bold")
            ax.set_xlabel("Frame")
            ax.set_ylabel("Movement score")
            ax.grid(True, alpha=0.25)
            fig.tight_layout()
            name = "movement_chart.png"
            fig.savefig(folder / name, dpi=120)
            plt.close(fig)
            out["movement"] = name

        # -- Joint angles over time ----------------------------------
        if angles_file.exists():
            ang = pd.read_csv(angles_file)
            joint_groups = {
                "Elbow": ["left_elbow_angle", "right_elbow_angle"],
                "Knee": ["left_knee_angle", "right_knee_angle"],
                "Shoulder": ["left_shoulder_angle", "right_shoulder_angle"],
                "Hip": ["left_hip_angle", "right_hip_angle"],
            }
            base_x = ang["frame"].to_numpy()
            grid_cols = 2
            fig, axes = plt.subplots(
                2, grid_cols, figsize=(10, 6.6), dpi=120)
            axes = axes.flatten()
            palette = ["#3fa7ff", "#ff5e7a", "#35e0a1", "#ffc34d"]
            for i, (group, cols) in enumerate(joint_groups.items()):
                ax = axes[i]
                for cidx, col in enumerate(cols):
                    ax.plot(base_x, ang[col],
                            label=col.replace("_angle", ""),
                            color=palette[cidx], lw=1.4, alpha=0.9)
                ax.set_title(f"{group} Angles", fontweight="bold")
                ax.set_xlabel("Frame")
                ax.set_ylabel("Degrees")
                ax.legend(fontsize=7, loc="best")
                ax.grid(True, alpha=0.25)
            for j in range(len(joint_groups), len(axes)):
                axes[j].axis("off")
            fig.suptitle("Joint Angles Over Time", fontweight="bold")
            fig.tight_layout(rect=[0, 0, 1, 0.97])
            name = "joint_angles_chart.png"
            fig.savefig(folder / name, dpi=120)
            plt.close(fig)
            out["joint_angles"] = name

        # -- Phase distribution bar ----------------------------------
        counts = df["phase"].value_counts()
        order = ["Stance", "Backlift", "Downswing", "Impact",
                 "Follow-through"]
        order = [o for o in order if o in counts.index]
        vals = [counts[o] for o in order]
        cols = [CHART_COLORS.get(o, "#888") for o in order]
        fig, ax = plt.subplots(figsize=(8, 3.6), dpi=120)
        ax.bar(order, vals, color=cols, edgecolor="none")
        ax.set_title("Batting Phase Distribution (frames)", fontweight="bold")
        ax.set_xlabel("Phase")
        ax.set_ylabel("Frames")
        ax.grid(axis="y", alpha=0.25)
        for i, v in enumerate(vals):
            ax.text(i, v + 0.3, str(v), ha="center", fontweight="bold")
        fig.tight_layout()
        name = "phase_chart.png"
        fig.savefig(folder / name, dpi=120)
        plt.close(fig)
        out["phase"] = name

    except Exception as exc:
        print(f"[make_results_charts] {exc}")

    return out
@app.route("/reports/<path:filename>")
def report_file(filename):
    return send_from_directory(REPORTS_DIR, filename)


@app.route("/output/<video_name>/<filename>")
def result_image(video_name, filename):
    folder = OUTPUT_DATA / Path(video_name).name
    if not folder.exists():
        abort(404)
    return send_from_directory(folder, filename)


@app.route("/output_video/<video_name>")
def output_video_file(video_name):
    """Serve the annotated analysis video for a processed clip."""
    file_name = f"{Path(video_name).stem}_analysis.mp4"
    if not (OUTPUT_VIDEOS / file_name).exists():
        abort(404)
    return send_from_directory(OUTPUT_VIDEOS, file_name)


@app.route("/generate_analysis/<video_name>", methods=["POST"])
def generate_analysis(video_name):
    """Render the annotated analysis video on demand for a processed clip."""
    ok = ensure_analysis_video(video_name)
    if ok:
        flash("Analysis video generated.", "success")
    else:
        flash("Could not generate the analysis video for this clip.", "error")
    return redirect(url_for("results", video_name=video_name))


def ensure_analysis_video(video_name):
    """Ensure the annotated analysis video exists for a clip.

    If it is missing, it is rebuilt from the existing per-video CSVs
    (no MediaPipe re-run) via ``output_video.py`` (H.264, browser-playable).
    Runs headless: no OpenCV window, no child console. Returns True on success.
    """
    video_name = Path(video_name).stem
    out = OUTPUT_VIDEOS / f"{video_name}_analysis.mp4"
    if out.exists() and analysis_video_is_ready(out):
        return True

    source = None
    for folder in INPUT_VIDEOS.rglob("*"):
        if folder.is_file() and folder.stem == video_name \
                and not is_generated_video(folder.name):
            source = folder
            break
    if source is None:
        return False

    shot_type = source.parent.name
    temp_out = out.with_name(f"{out.stem}.regenerating.mp4")
    try:
        temp_out.unlink(missing_ok=True)
    except OSError as exc:
        print(f"[ensure_analysis_video] could not clear temporary output: {exc}")
        return False
    command = [
        sys.executable,
        str(BASE_DIR / "output_video.py"),
        str(source),
        shot_type,
        str(temp_out),
    ]
    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            cwd=str(BASE_DIR),
            timeout=900,
            creationflags=config.NO_CONSOLE_FLAGS,
        )
        if result.returncode != 0 or not temp_out.exists():
            return False
        try:
            os.replace(temp_out, out)
        except OSError as exc:
            print(f"[ensure_analysis_video] could not replace output: {exc}")
            return False
        return True
    except Exception as exc:
        print(f"[ensure_analysis_video] {exc}")
        return False


def analysis_video_is_ready(path):
    """Return whether an analysis video is readable and non-empty.

    Reliability only - the duration/frame-fidelity of the output is guaranteed
    by output_video.py's VIDEO VALIDATION block, not by a minimum-seconds
    gate here. Short clips are valid and must not be hidden or padded.
    """
    capture = cv2.VideoCapture(str(path))
    try:
        fps = capture.get(cv2.CAP_PROP_FPS)
        frames = capture.get(cv2.CAP_PROP_FRAME_COUNT)
        return fps > 0 and frames > 0
    finally:
        capture.release()


# --------------------------------------------------------------------------
# Batch processing
# --------------------------------------------------------------------------

def _run_video_task(task):
    """Standalone, picklable worker for ProcessPoolExecutor.

    Runs the full pipeline for one video via ``process_video.py`` and returns
    its name, detected shot type and success flag. Nothing mutable shared
    across processes is used - only the filesystem side-effect of the run.
    """
    video_path, shot_type = task
    video_name = Path(video_path).stem
    command = [
        sys.executable,
        str(BASE_DIR / "process_video.py"),
        str(video_path),
    ]
    try:
        env = dict(os.environ)
        env["PYTHONUNBUFFERED"] = "1"
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            cwd=str(BASE_DIR),
            env=env,
            timeout=config.PIPELINE_TIMEOUT,
            creationflags=config.NO_CONSOLE_FLAGS,
        )
        return video_name, shot_type, result.returncode == 0
    except Exception as exc:
        print(f"[batch] {video_name} failed: {exc}")
        return video_name, shot_type, False


def _batch_worker(batch_id, workers):
    """Process all input videos in parallel using ProcessPoolExecutor."""
    batch = BATCH_JOBS[batch_id]
    batch["started_at"] = time.time()
    batch["current"] = "Scanning input videos…"

    # Discover all input videos (generated analysis files are never inputs)
    video_tasks = []
    for folder in INPUT_VIDEOS.iterdir():
        if not folder.is_dir():
            continue
        shot_type = normalise_shot_type(folder.name) or folder.name
        for vid in folder.iterdir():
            if vid.is_file() and is_generated_video(vid.name):
                continue
            if vid.suffix.lower() in {".mp4", ".avi", ".mov", ".mkv"}:
                video_tasks.append((vid, shot_type))

    if not video_tasks:
        with BATCH_JOBS_LOCK:
            batch["done"] = True
            batch["ok"] = True
            batch["current"] = "No input videos found."
            batch["finished_at"] = time.time()
        return

    batch["total"] = len(video_tasks)
    batch["completed"] = 0
    batch["results"] = []
    batch["ok"] = True

    try:
        from concurrent.futures import ProcessPoolExecutor, as_completed
        max_workers = max(1, min(int(workers), len(video_tasks)))
        with ProcessPoolExecutor(max_workers=max_workers) as pool:
            futures = [pool.submit(_run_video_task, t) for t in video_tasks]
            for f in as_completed(futures):
                video_name, shot_type, ok = f.result()
                with BATCH_JOBS_LOCK:
                    batch["completed"] += 1
                    batch["ok"] = batch["ok"] and ok
                    batch["results"].append({
                        "name": video_name,
                        "shot_type": shot_type,
                        "ok": ok,
                    })
                    batch["current"] = (
                        f"{batch['completed']}/{batch['total']} done — "
                        f"latest: {video_name}"
                    )
    except Exception as exc:
        print(f"[batch] batch {batch_id} crashed: {exc}")
        batch["error"] = str(exc)
        batch["ok"] = False

    with BATCH_JOBS_LOCK:
        batch["done"] = True
        batch["current"] = "Batch complete." if batch["ok"] else "Batch failed."
        batch["finished_at"] = time.time()


@app.route("/batch_process", methods=["POST"])
def batch_process():
    """Kick off parallel re-processing of all input videos."""
    workers = request.form.get("workers", config.MAX_WORKERS, type=int)
    workers = max(1, min(workers, 16))

    batch_id = uuid.uuid4().hex[:12]
    batch = {
        "done": False,
        "ok": False,
        "total": 0,
        "completed": 0,
        "results": [],
        "current": "Starting…",
        "error": None,
        "started_at": None,
        "finished_at": None,
    }
    with BATCH_JOBS_LOCK:
        BATCH_JOBS[batch_id] = batch

    thread = threading.Thread(
        target=_batch_worker, args=(batch_id, workers), daemon=True
    )
    thread.start()
    return redirect(url_for("batch_status", batch_id=batch_id))


@app.route("/batch_status/<batch_id>")
def batch_status(batch_id):
    batch = BATCH_JOBS.get(batch_id)
    if batch is None:
        flash("That batch job is no longer available.", "error")
        return redirect(url_for("dashboard"))
    return render_template("batch_status.html",
                           batch_id=batch_id, batch=batch)


@app.route("/batch_status_json/<batch_id>")
def batch_status_json(batch_id):
    batch = BATCH_JOBS.get(batch_id)
    if batch is None:
        return {"state": "missing"}
    return {
        "state": "done" if batch.get("done") else "running",
        "ok": batch.get("ok"),
        "total": batch.get("total", 0),
        "completed": batch.get("completed", 0),
        "current": batch.get("current", ""),
        "error": batch.get("error"),
        "results": batch.get("results", []),
    }


# --------------------------------------------------------------------------
# Pages
# --------------------------------------------------------------------------
@app.context_processor
def inject_globals():
    stats = load_dataset_stats()
    return {
        "shot_types": SHOT_TYPES,
        "dataset_count": stats["total_videos"],
    }


@app.route("/dashboard")
def dashboard():
    stats = load_dataset_stats()

    eda_images = []
    eda_dir = REPORTS_DIR / "eda"
    if eda_dir.exists():
        eda_images = sorted(p.name for p in eda_dir.glob("*.png"))

    # Only read text files into model_files. Binary images are served
    # directly by the report_file route and must not be read as text.
    text_files = [
        "model_comparison.csv",
        "feature_importance.csv",
        "classification_report.txt",
        "model_results_summary.txt",
    ]
    model_files = {}
    for name in text_files:
        p = REPORTS_DIR / name
        model_files[name] = (
            p.read_text(encoding="utf-8") if p.exists() else None
        )
    model_files["confusion_matrix.png"] = (
        (REPORTS_DIR / "confusion_matrix.png").exists()
    )
    model_files["feature_importance.png"] = (
        (REPORTS_DIR / "feature_importance.png").exists()
    )

    return render_template(
        "dashboard.html",
        stats=stats,
        eda_images=eda_images,
        model_files=model_files,
        recent_videos=load_recent_videos(),
        ml_insights=load_ml_insights(),
    )


@app.route("/history")
def history():
    """Full history of every processed analysis, newest first."""
    videos = _list_processed_videos()
    return render_template(
        "history.html",
        videos=videos,
        total=len(videos),
        rated_count=sum(1 for v in videos if v["rating"] is not None),
    )


@app.route("/upload", methods=["GET"])
def upload_form():
    return render_template("upload.html")


def _handle_upload_request(file, shot_type):
    """Stage, dedup and schedule an uploaded video for processing.

    Shared by the HTML form and the JSON API so both routes behave exactly
    alike. Returns a dict describing the outcome; callers translate it into
    either a redirect+flash (HTML) or a JSON response.
    """
    shot_type = normalise_shot_type(shot_type)
    if shot_type is None:
        return {"kind": "invalid_shot", "message": "Please select a valid shot type."}

    if file is None or file.filename in (None, ""):
        return {"kind": "no_file", "message": "No file selected."}

    if not allowed_file(file.filename):
        return {
            "kind": "bad_ext",
            "message": "Unsupported file type. Allowed: "
                       + ", ".join(sorted(ALLOWED_EXTENSIONS)),
        }

    stem = safe_filename(Path(file.filename).stem)
    ext = Path(file.filename).suffix.lower()

    # ---- Stage the upload in the temp folder (never in input_videos). ----
    # The file only reaches input_videos/<shot_type>/ exactly once, after the
    # content-hash dedup below. Partial/failed/duplicate uploads therefore can
    # never pollute the input tree or the ML dataset.
    config.UPLOADS.mkdir(parents=True, exist_ok=True)
    tmp_path = config.UPLOADS / f"{uuid.uuid4().hex}-{stem}{ext}"
    try:
        file.save(tmp_path)
    except Exception as exc:
        print(f"[upload] staging save failed: {exc}")
        tmp_path.unlink(missing_ok=True)
        return {"kind": "save_error", "message": "Could not save the uploaded file."}

    digest = video_content_hash(tmp_path)

    # ---- Dedup + atomic move (serialised to make it race-free). ----------
    with UPLOAD_LOCK:
        if digest in INFLIGHT_UPLOADS:
            tmp_path.unlink(missing_ok=True)
            return {
                "kind": "inflight",
                "message": "This clip was already submitted and is being processed.",
            }

        existing_source = find_existing_video(tmp_path, digest)
        if existing_source is not None:
            tmp_path.unlink(missing_ok=True)
            existing_name = existing_source.stem
            if (OUTPUT_DATA / existing_name).exists():
                return {
                    "kind": "existing_results",
                    "video_name": existing_name,
                    "message": "This video was already analysed.",
                }
            return {
                "kind": "existing_processing",
                "message": "This video is already being processed.",
            }

        target_folder = INPUT_VIDEOS / shot_type
        target = make_unique_path(target_folder, stem, ext)
        try:
            import shutil
            shutil.move(str(tmp_path), str(target))
        except Exception as exc:
            print(f"[upload] move failed: {exc}")
            tmp_path.unlink(missing_ok=True)
            return {"kind": "move_error", "message": "Could not save the uploaded file."}

        INFLIGHT_UPLOADS.add(digest)

    video_name = target.stem

    # Launch the pipeline as a background job so the browser never blocks.
    _prune_old_jobs()
    job_id = uuid.uuid4().hex[:12]
    job = {
        "video_path": str(target),
        "video_name": video_name,
        "shot_type": shot_type,
        "digest": digest,
        "steps": [],
        "current": "Queued…",
        "done": False,
        "ok": False,
        "error": None,
        "started_at": None,
        "finished_at": None,
    }
    with PIPELINE_JOBS_LOCK:
        PIPELINE_JOBS[job_id] = job
    thread = threading.Thread(target=_pipeline_worker, args=(job_id,), daemon=True)
    thread.start()

    return {
        "kind": "queued",
        "job_id": job_id,
        "video_name": video_name,
        "shot_type": shot_type,
    }


@app.route("/upload", methods=["POST"])
def upload_submit():

    shot_type = request.form.get("shot_type", "").strip().lower()
    outcome = _handle_upload_request(request.files.get("video"), shot_type)

    if outcome["kind"] == "queued":
        return redirect(url_for(
            "progress", job_id=outcome["job_id"], shot_type=outcome["shot_type"]
        ))

    if outcome["kind"] == "inflight":
        flash(outcome["message"], "info")
        return redirect(url_for("dashboard"))

    if outcome["kind"] == "existing_results":
        flash(outcome["message"], "info")
        return redirect(url_for("results", video_name=outcome["video_name"]))

    if outcome["kind"] == "existing_processing":
        flash(outcome["message"], "info")
        return redirect(url_for("dashboard"))

    if outcome["kind"] == "invalid_shot":
        flash(outcome["message"], "error")

    if outcome["kind"] == "no_file":
        flash(outcome["message"], "error")

    if outcome["kind"] == "bad_ext":
        flash(outcome["message"], "error")

    if outcome["kind"] in ("save_error", "move_error"):
        flash(outcome["message"], "error")

    return redirect(url_for("upload_form"))


@app.route("/progress/<job_id>")
def progress(job_id):
    job = PIPELINE_JOBS.get(job_id)
    if job is None:
        flash("That processing job is no longer available.", "error")
        return redirect(url_for("dashboard"))
    return render_template(
        "progress.html",
        job_id=job_id,
        video_name=job["video_name"],
        shot_type=job.get("shot_type", ""),
        shot_type_label=SHOT_TYPE_LABELS.get(job.get("shot_type", ""), "Unknown"),
    )


@app.route("/progress_status/<job_id>")
def progress_status(job_id):
    job = PIPELINE_JOBS.get(job_id)
    if job is None:
        return {"state": "missing"}
    return {
        "state": "done" if job.get("done") else "running",
        "ok": job.get("ok"),
        "steps": job.get("steps", []),
        "current": job.get("current", "Starting…"),
        "error": job.get("error"),
        "video_name": job.get("video_name"),
        "shot_type": job.get("shot_type", ""),
    }


@app.route("/results/<video_name>")
def results(video_name):
    video_name = Path(video_name).name  # never use an unsanitised FS path
    shot_type = request.args.get("shot_type", "").strip().lower() or "unknown"

    data = load_video_results(video_name)
    if not data["found"]:
        flash("No results found for that video.", "error")
        return redirect(url_for("dashboard"))

    plot_name = make_angle_plot(video_name)
    charts = make_results_charts(video_name)
    phase_timeline = load_phase_timeline(video_name)

    analysis_video = OUTPUT_VIDEOS / f"{video_name}_analysis.mp4"
    has_analysis = analysis_video.exists() and analysis_video_is_ready(analysis_video)

    return render_template(
        "results.html",
        data=data,
        shot_type=shot_type,
        shot_type_label=SHOT_TYPE_LABELS.get(shot_type, shot_type or "Unknown"),
        impact_angle_labels=IMPACT_ANGLE_LABELS,
        impact_angle_columns=IMPACT_ANGLE_COLUMNS,
        plot_name=plot_name,
        charts=charts,
        phase_timeline=phase_timeline,
        injury=load_injury_data(video_name),
        has_analysis=has_analysis,
        ml_insights=load_ml_insights(),
        recent_videos=load_recent_videos(),
    )


# --------------------------------------------------------------------------
# JSON API (consumed by the Kinetic.AI React dashboard)
# --------------------------------------------------------------------------
def _num(value, default=None):
    """Coerce numpy/Pandas scalars into plain JSON-safe numbers."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _json_safe(value):
    """Best-effort conversion of a nested dict/list to JSON-serialisable data."""
    import math
    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        if isinstance(value, float) and not math.isfinite(value):
            return None
        return value
    if value is None:
        return None
    try:
        return value.item() if hasattr(value, "item") else value
    except Exception:
        return str(value)


@app.route("/api/stats")
def api_stats():
    stats = load_dataset_stats()
    return jsonify({
        "total_videos": stats["total_videos"],
        "n_classes": stats["n_classes"],
        "class_names": stats["class_names"],
        "distribution": {str(k): int(v) for k, v in stats["distribution"].items()},
        "n_features": stats["n_features"],
        "dataset_exists": stats["dataset_exists"],
        "has_ml_reports": stats.get("has_ml_reports", {}),
        "ml": load_ml_insights(),
    })


@app.route("/api/videos")
def api_videos():
    videos = _list_processed_videos()
    for v in videos:
        v["analysis_url"] = url_for("output_video_file", video_name=v["name"]) \
            if v.get("analysis_exists") else None
        v["results_url"] = url_for("api_results", video_name=v["name"])
    return jsonify({
        "count": len(videos),
        "videos": videos,
    })


@app.route("/api/history")
def api_history():
    videos = _list_processed_videos()
    return jsonify({
        "total": len(videos),
        "rated_count": sum(1 for v in videos if v["rating"] is not None),
        "videos": videos,
    })


@app.route("/api/ml")
def api_ml():
    return jsonify(_json_safe(load_ml_insights()))


@app.route("/api/reports")
def api_reports():
    eda_images = []
    eda_dir = REPORTS_DIR / "eda"
    if eda_dir.exists():
        for p in sorted(eda_dir.glob("*.png")):
            eda_images.append({
                "name": p.name,
                "url": url_for("report_file", filename=f"eda/{p.name}"),
            })

    text_files = {
        "classification_report.txt",
        "model_results_summary.txt",
        "data_quality.txt",
        "error_analysis.txt",
        "robustness.txt",
        "scientific_validity.txt",
        "feature_importance.csv",
        "model_comparison.csv",
    }
    documents = {}
    for name in sorted(text_files):
        p = REPORTS_DIR / name
        if p.exists():
            text = p.read_text(encoding="utf-8", errors="replace")
            documents[name] = text[:60000]

    images = {}
    for name in ("confusion_matrix.png", "feature_importance.png"):
        p = REPORTS_DIR / name
        images[name] = (
            url_for("report_file", filename=name) if p.exists() else None
        )

    return jsonify({
        "eda_images": eda_images,
        "images": images,
        "documents": documents,
        "stats": load_dataset_stats(),
    })


def _results_payload(video_name):
    """JSON payload for a single processed video (used by api_results)."""
    shot_type = ""
    for folder_candidate in INPUT_VIDEOS.rglob(f"{video_name}.*"):
        if folder_candidate.is_file() and not is_generated_video(
                folder_candidate.name):
            shot_type = normalise_shot_type(folder_candidate.parent.name) or ""
            break
    if shot_type == "":
        for sub in SHOT_TYPES:
            if (INPUT_VIDEOS / sub / video_name).exists():
                shot_type = sub
                break

    data = load_video_results(video_name)
    if not data["found"]:
        return None

    plot_name = make_angle_plot(video_name)
    charts = make_results_charts(video_name)
    phase_timeline = load_phase_timeline(video_name)
    injury = load_injury_data(video_name)
    classification = load_shot_classification(video_name)
    analysis_video = OUTPUT_VIDEOS / f"{video_name}_analysis.mp4"
    has_analysis = analysis_video.exists() and \
        analysis_video_is_ready(analysis_video)

    metric_round = {
        "downswing_duration_ms", "followthrough_duration_ms",
        "impact_frame", "impact_time_ms", "maximum_movement_score",
        "average_movement_score",
    }
    metrics = {}
    for k, v in data["metrics"].items():
        num = _num(v)
        if num is not None and k in metric_round:
            num = round(num, 1)
        metrics[k] = num

    return {
        "video_name": video_name,
        "shot_type": shot_type or "unknown",
        "shot_type_label": SHOT_TYPE_LABELS.get(shot_type, shot_type or "Unknown"),
        # Model-based classification. `classification["shot_type"]` is the
        # classifier's own answer and is "unknown" when it is not confident
        # about a supported shot; the folder-derived `shot_type` above is the
        # label the clip was filed under.
        "classification": _json_safe(classification),
        "found": True,
        "frames": data["frames"],
        "metrics": metrics,
        "features": {k: _num(v) for k, v in data["features"].items()},
        "impact_angles": {
            k: round(_num(v), 1) if _num(v) is not None else None
            for k, v in data["impact_angles"].items()
        },
        "impact_angle_labels": IMPACT_ANGLE_LABELS,
        "impact_angle_columns": IMPACT_ANGLE_COLUMNS,
        "rating": _json_safe(data["rating"]),
        "injury": _json_safe(injury),
        "phase_timeline": _json_safe(phase_timeline),
        "charts": charts,
        "plot": plot_name,
        "has_analysis": has_analysis,
        "analysis_url": url_for(
            "output_video_file", video_name=video_name) if has_analysis else None,
        "output_base": url_for(
            "result_image", video_name=video_name, filename="") ,
        "ml": load_ml_insights(),
    }


@app.route("/api/results/<video_name>")
def api_results(video_name):
    video_name = Path(video_name).name
    payload = _results_payload(video_name)
    if payload is None:
        return jsonify({"found": False, "video_name": video_name}), 404
    return jsonify(payload)


@app.route("/api/progress/<job_id>")
def api_progress(job_id):
    job = PIPELINE_JOBS.get(job_id)
    if job is None:
        return jsonify({"state": "missing"})
    return jsonify({
        "state": "done" if job.get("done") else "running",
        "ok": job.get("ok"),
        "steps": job.get("steps", []),
        "current": job.get("current", "Starting…"),
        "error": job.get("error"),
        "video_name": job.get("video_name"),
        "shot_type": job.get("shot_type", ""),
    })


@app.route("/api/upload", methods=["POST"])
def api_upload():
    shot_type = request.form.get("shot_type", "").strip().lower()
    outcome = _handle_upload_request(request.files.get("video"), shot_type)
    if outcome["kind"] == "queued":
        return jsonify({
            "status": "queued",
            "job_id": outcome["job_id"],
            "video_name": outcome["video_name"],
            "shot_type": outcome["shot_type"],
        })
    if outcome["kind"] == "existing_results":
        return jsonify({
            "status": "existing",
            "video_name": outcome["video_name"],
            "message": outcome["message"],
        })
    if outcome["kind"] == "existing_processing":
        return jsonify({"status": "duplicate", "message": outcome["message"]}), 409
    if outcome["kind"] == "inflight":
        return jsonify({"status": "inflight", "message": outcome["message"]}), 409
    return jsonify({"status": "error", "message": outcome["message"]}), 400


@app.route("/api/dataset.csv")
def api_dataset_csv():
    """Download the engineered biomechanics dataset as CSV."""
    candidates = [
        OUTPUT_DATA / "cricket_biomechanics_dataset_engineered.csv",
        OUTPUT_DATA / "cricket_biomechanics_dataset_cleaned.csv",
        OUTPUT_DATA / "cricket_biomechanics_dataset.csv",
    ]
    for path in candidates:
        if path.exists():
            return send_file(path, as_attachment=True,
                             download_name=path.name)
    abort(404)


# --------------------------------------------------------------------------
# SPA: serve the built Kinetic.AI React dashboard when dist is present.
# --------------------------------------------------------------------------
@app.route("/")
def index():
    index_file = WEB_DIST / "index.html"
    if index_file.exists():
        return send_from_directory(WEB_DIST, "index.html")
    stats = load_dataset_stats()
    return render_template("index.html", stats=stats)


@app.route("/<path:path>")
def spa_fallback(path):
    """Serve built frontend assets, falling back to the SPA shell."""
    if (WEB_DIST / "index.html").exists():
        target = WEB_DIST / path
        if target.is_file():
            return send_from_directory(WEB_DIST, path)
        return send_from_directory(WEB_DIST, "index.html")
    abort(404)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
