from pathlib import Path
import os
import subprocess
import sys

BASE_DIR = Path(__file__).resolve().parent

# Filename suffixes generated by the pipeline (analysis videos, transcode
# intermediates). Any file matching one of these is NEVER treated as an input
# clip: upload dedup and the batch workers skip them so freshly generated
# analysis videos can never be re-uploaded / re-processed.
GENERATED_SUFFIXES = (
    "_analysis",
    "_processed",
    "_output",
    "_labeled",
    "_annotated",
    "_regenerating",
)


def is_generated_filename(filename):
    """Return True when a filename belongs to a generated pipeline output."""
    stem = Path(filename).stem.lower()
    return any(stem.endswith(sfx) for sfx in GENERATED_SUFFIXES)

# Pose detection runs on every detected frame. The two-pass temporal tracker
# detects ALL frames so the batsman identity lock is never left to stale
# poses; stride must stay 1 for honest tracking. Override with the
# CBAI_POSE_STRIDE environment variable (kept only for low-power fallbacks).
def _default_pose_stride():
    import os
    raw = os.environ.get("CBAI_POSE_STRIDE", "1")
    try:
        return max(1, int(raw))
    except ValueError:
        return 1

POSE_STRIDE = _default_pose_stride()

INPUT_VIDEO = BASE_DIR / "input_videos" / "cut" / "cut1.avi"

OUTPUT_VIDEO = BASE_DIR / "output_videos" / "processed_batting.mp4"

OUTPUT_DATA = BASE_DIR / "output_data"

REPORTS = BASE_DIR / "reports"

# Annotated analysis videos live in the dedicated output folder, NEVER inside
# input_videos. Keeping generated videos out of the input tree is what stops
# the batch worker / process_all.py from re-uploading (and re-processing)
# freshly generated analysis files.
ANALYSIS_VIDEOS = BASE_DIR / "output_videos"

# Legacy alias used by the web app for serving/serving-checking analysis files.
OUTPUT_VIDEOS = ANALYSIS_VIDEOS

# ---------------------------------------------------------------------------
# Frame pre-processing (pose-detection robustness)
# ---------------------------------------------------------------------------
# CLAHE contrast enhancement applied to every frame *before* pose detection so
# dark / unevenly-lit clips still yield reliable keypoints. It is
# geometry-preserving (only pixel intensity changes; normalized landmark
# coordinates, angles and phase windows stay valid) but costs a little CPU.
# Override with CBAI_PREPROCESS_ENABLE / CBAI_PREPROCESS_CLAHE_CLIP /
# CBAI_PREPROCESS_CLAHE_GRID.
def _env_bool(name, default):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_float(name, default):
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def _env_int(name, default):
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


PREPROCESS_ENABLE = _env_bool("CBAI_PREPROCESS_ENABLE", True)
PREPROCESS_CLAHE_CLIP = _env_float("CBAI_PREPROCESS_CLAHE_CLIP", 2.0)
PREPROCESS_CLAHE_GRID = max(1, _env_int("CBAI_PREPROCESS_CLAHE_GRID", 8))

# Temporary staging folder for uploads BEFORE they are validated and moved
# into input_videos/<shot_type>/ exactly once. Files here are never scanned
# by the pipeline, so partial/duplicate uploads cannot pollute the dataset.
UPLOADS = BASE_DIR / "uploads"

# Creation flags for subprocess calls. On Windows this stops child python
# processes from flashing their own console window next to the web app.
NO_CONSOLE_FLAGS = 0
if sys.platform == "win32":
    NO_CONSOLE_FLAGS = subprocess.CREATE_NO_WINDOW


# Maximum number of videos to process in parallel. Each worker is a separate
# Python process that loads its own MediaPipe + OpenCV stack (~400 MB RAM).
# Override with the CBAI_MAX_WORKERS environment variable.
def _default_max_workers():
    raw = os.environ.get("CBAI_MAX_WORKERS")
    if raw:
        try:
            return max(1, int(raw))
        except ValueError:
            pass
    cpus = os.cpu_count() or 4
    return min(cpus, 8)


MAX_WORKERS = _default_max_workers()

# Per-video timeout (seconds) for a full pipeline run spawned from the web
# app's parallel batch endpoint. Long enough for slow pose inference on
# long clips; override with CBAI_PIPELINE_TIMEOUT.
def _default_pipeline_timeout():
    raw = os.environ.get("CBAI_PIPELINE_TIMEOUT")
    if raw:
        try:
            return max(60, int(raw))
        except ValueError:
            pass
    return 1800


PIPELINE_TIMEOUT = _default_pipeline_timeout()